import { type Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
	metadataBase: new URL('http://localhost:3000'),
	alternates: {
		canonical: './'
	},
	openGraph: {
		url: './'
	}
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
